blank_issues_enabled: false
contact_links:
  - name: Discord server
    url: https://discord.gg/GsEFRM8
    about: Please visit our Discord server (and come to \#mineflayer) for questions and support requests.
